/**
 * Keeps generated contract artifacts in sync with the Solidity sources.
 *
 *   node scripts/artifacts.ts abi [--check] [--stage]
 *     Builds with forge, then writes the ABI to abi/, ts/generated/ and the web app.
 *     --check exits non-zero instead of writing when anything is out of date.
 *     --stage adds rewritten files to the git index (used by the pre-commit hook).
 *
 *   node scripts/artifacts.ts deployments
 *     Records every broadcast of script/Deploy.s.sol into deployments/<chainId>.json and
 *     regenerates ts/generated/deployments.ts.
 */
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { contractDeploymentSchema, findChain, type ContractDeployment } from "@fairdrops/shared";
import { z } from "zod";

const CONTRACT = "FairDrops";
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageRoot, "../..");

const paths = {
  source: join(packageRoot, "src", `${CONTRACT}.sol`),
  artifact: join(packageRoot, "out", `${CONTRACT}.sol`, `${CONTRACT}.json`),
  abiJson: join(packageRoot, "abi", `${CONTRACT}.json`),
  generatedAbi: join(packageRoot, "ts", "generated", "abi.ts"),
  generatedDeployments: join(packageRoot, "ts", "generated", "deployments.ts"),
  webAbi: join(repoRoot, "apps", "web", "abi", "fairDrops.ts"),
  deployments: join(packageRoot, "deployments"),
  broadcast: join(packageRoot, "broadcast", "Deploy.s.sol"),
};

const HEADER = "// Generated by packages/contracts/scripts/artifacts.ts. Do not edit.\n";

const abiSchema = z.array(z.record(z.string(), z.unknown()));
const artifactSchema = z.object({ abi: abiSchema });

const hexSchema = z.string().regex(/^0x[0-9a-fA-F]*$/);
const broadcastSchema = z.object({
  timestamp: z.number(),
  transactions: z.array(
    z.object({
      hash: hexSchema,
      transactionType: z.string(),
      contractName: z.string().nullable(),
      contractAddress: hexSchema.nullable(),
      transaction: z.object({
        from: hexSchema,
        input: hexSchema.optional(),
        data: hexSchema.optional(),
      }),
    }),
  ),
  receipts: z.array(
    z.object({ transactionHash: hexSchema, blockNumber: hexSchema, status: hexSchema }),
  ),
});

function main(): void {
  const [command, ...flags] = process.argv.slice(2);
  if (command === "abi") {
    syncAbi({ check: flags.includes("--check"), stage: flags.includes("--stage") });
  } else if (command === "deployments") {
    exportDeployments();
  } else {
    fail(`Unknown command "${command ?? ""}". Expected "abi" or "deployments".`);
  }
}

function syncAbi({ check, stage }: { check: boolean; stage: boolean }): void {
  if (hasForge()) {
    const build = spawnSync("forge", ["build"], { cwd: packageRoot, encoding: "utf8" });
    if (build.status !== 0) fail(`forge build failed:\n${build.stdout}${build.stderr}`);
  } else if (check || !existsSync(paths.artifact)) {
    fail(
      "forge is not installed, so the ABI cannot be rebuilt. Install Foundry: https://getfoundry.sh",
    );
  } else {
    warn("forge is not installed; syncing the ABI from the existing build output.");
  }

  const { abi } = artifactSchema.parse(readJson(paths.artifact));
  const hash = abiHash(abi);
  const module = abiModule(abi, hash);

  const outputs: Array<[string, string]> = [
    [paths.abiJson, `${JSON.stringify(abi, null, 2)}\n`],
    [paths.generatedAbi, module],
    [paths.webAbi, module],
  ];
  const changed = outputs
    .filter(([file, content]) => readText(file) !== content)
    .map(([file]) => file);

  if (check) {
    if (changed.length > 0) {
      fail(
        `Contract ABI is out of date in:\n${changed.map((f) => `  ${relative(repoRoot, f)}`).join("\n")}\n` +
          "Run `pnpm --filter @fairdrops/contracts abi:sync` and commit the result.",
      );
    }
    log("Contract ABI is up to date.");
    return;
  }

  for (const [file, content] of outputs) {
    if (changed.includes(file)) writeText(file, content);
  }
  if (changed.length === 0) {
    log("Contract ABI unchanged.");
    return;
  }
  log(
    `Updated contract ABI (${hash.slice(0, 10)}):\n${changed.map((f) => `  ${relative(repoRoot, f)}`).join("\n")}`,
  );
  if (stage) execFileSync("git", ["add", "--", ...changed], { cwd: repoRoot, stdio: "inherit" });
}

function exportDeployments(): void {
  const abi = abiSchema.parse(readJson(paths.abiJson));
  const hash = abiHash(abi);
  const version = contractVersion();

  if (existsSync(paths.broadcast)) {
    for (const chainDir of readdirSync(paths.broadcast)) {
      const runFile = join(paths.broadcast, chainDir, "run-latest.json");
      if (!existsSync(runFile)) continue;
      const chain = findChain(Number(chainDir));
      if (!chain)
        fail(`Chain ${chainDir} is not in the registry in packages/shared/src/chains.ts.`);
      // Local chains are reset constantly; their addresses never belong in committed artifacts.
      if (chain.environment === "local") continue;
      const deployment = deploymentFromBroadcast(Number(chainDir), runFile, version, hash);
      if (!deployment) continue;

      const target = join(paths.deployments, `${deployment.chainId}.json`);
      const existing = readText(target);
      if (
        existing &&
        contractDeploymentSchema.parse(JSON.parse(existing)).address === deployment.address
      ) {
        continue;
      }
      writeText(target, `${JSON.stringify(deployment, null, 2)}\n`);
      log(`Recorded ${CONTRACT} on chain ${deployment.chainId} at ${deployment.address}`);
    }
  }

  const deployments = readdirSync(paths.deployments)
    .filter((file) => file.endsWith(".json"))
    .map((file) => contractDeploymentSchema.parse(readJson(join(paths.deployments, file))))
    .sort((a, b) => a.chainId - b.chainId);

  writeText(
    paths.generatedDeployments,
    `${HEADER}import type { ContractDeployment } from "@fairdrops/shared";\n\n` +
      `export const deployments: readonly ContractDeployment[] = ${JSON.stringify(deployments, null, 2)};\n`,
  );
  log(
    `Wrote ${deployments.length} deployment(s) to ${relative(repoRoot, paths.generatedDeployments)}`,
  );
}

function deploymentFromBroadcast(
  chainId: number,
  runFile: string,
  version: string,
  hash: string,
): ContractDeployment | null {
  const run = broadcastSchema.parse(readJson(runFile));
  const tx = run.transactions.find(
    (t) => t.contractName === CONTRACT && t.transactionType === "CREATE2",
  );
  if (!tx?.contractAddress) return null;

  const receipt = run.receipts.find(
    (r) => r.transactionHash.toLowerCase() === tx.hash.toLowerCase(),
  );
  if (!receipt)
    fail(`No receipt for ${tx.hash} on chain ${chainId}; was the broadcast interrupted?`);
  if (BigInt(receipt.status) !== 1n) fail(`Deployment ${tx.hash} on chain ${chainId} reverted.`);

  // The deterministic deployer takes the salt as the first 32 bytes of calldata.
  const input = tx.transaction.input ?? tx.transaction.data ?? "";
  const salt = `0x${input.slice(2, 66)}`;
  const timestampMs = run.timestamp > 1e12 ? run.timestamp : run.timestamp * 1000;

  return contractDeploymentSchema.parse({
    contract: CONTRACT,
    version,
    chainId,
    address: tx.contractAddress,
    transactionHash: tx.hash,
    blockNumber: Number(BigInt(receipt.blockNumber)),
    deployer: tx.transaction.from,
    salt,
    abiHash: hash,
    deployedAt: new Date(timestampMs).toISOString(),
  });
}

function abiModule(abi: unknown[], hash: string): string {
  return (
    `${HEADER}\n` +
    `export const fairDropsAbiHash = "${hash}" as const;\n\n` +
    `export const fairDropsAbi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

function abiHash(abi: unknown[]): string {
  return `0x${createHash("sha256").update(JSON.stringify(abi)).digest("hex")}`;
}

function contractVersion(): string {
  const match = /string public constant VERSION = "([^"]+)";/.exec(
    readFileSync(paths.source, "utf8"),
  );
  if (!match?.[1]) fail(`Could not read VERSION from ${relative(repoRoot, paths.source)}`);
  return match[1];
}

function hasForge(): boolean {
  return spawnSync("forge", ["--version"], { stdio: "ignore" }).status === 0;
}

function readJson(file: string): unknown {
  return JSON.parse(readFileSync(file, "utf8"));
}

function readText(file: string): string | null {
  return existsSync(file) ? readFileSync(file, "utf8") : null;
}

function writeText(file: string, content: string): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
}

function log(message: string): void {
  process.stdout.write(`${message}\n`);
}

function warn(message: string): void {
  process.stderr.write(`warning: ${message}\n`);
}

function fail(message: string): never {
  process.stderr.write(`error: ${message}\n`);
  process.exit(1);
}

main();
