/** English UI copy. Later locales replace this module; do not scatter strings through components. */
export const copy = {
  join: "Join giveaway",
  joinNow: "Join now",
  joiningClosed: "Joining closed",
  youAreIn: "You're in",
  goToLobby: "Go to lobby",
  freeToJoin: "Free to join. No crypto needed.",
  continueGoogle: "Continue with Google",
  continueEmail: "Continue with email",
  haveWallet: "I already have a wallet",
  providerLater: "Google and email sign-in need a wallet provider that is not set up yet.",
  walletCreated: "We create a secure wallet for your prizes. You won't need to buy anything.",
  signInReason: "Sign in so we know where to send your prize.",
  noWallet: "No wallet found in this browser.",
  share: "Share",
  back: "Back",
  mute: "Mute game sounds",
  unmute: "Turn game sounds on",
  soundsOn: "Game sounds are on",
  soundsOff: "Game sounds are off",
  roll: "Roll the dice",
  rolling: "Rolling",
  doneNext: "Done · next game",
  scoresLock: "Scores lock when time is up",
  fairnessNote: "Top places across the games win. Scores are checked afterwards.",
  faster: "Faster right answers score more",
  right: "Right!",
  wrong: "Not this time.",
  collect: "Collect prize",
  collecting: "Collecting",
  shareWin: "Share win",
  discover: "Discover",
  prizes: "My prizes",
  hosting: "Hosting",
  developers: "Developers",
  hostGiveaway: "Host a giveaway",
  createGiveaway: "Create giveaway",
  emptyDiscover: "Nothing live right now.",
  emptyBoards: "Top gifters and top earners will show here once that list exists.",
  previewNote: "This is a local preview of the game order. Scores here are not recorded.",
  menu: "Menu",
  theme: "Theme",
  comingSoon: "Coming soon",
  signIn: {
    wallet: "Connect a wallet",
    note: "Signing in only asks your wallet to sign a message. It never sends money or costs a fee.",
    developersTitle: "Sign in to manage your games",
    developersReason: "Register games, create API keys and see how your games are used.",
    hostingTitle: "Sign in to see your giveaways",
    hostingReason: "Track the giveaways you've hosted, add to prizes and withdraw what's left.",
    prizesTitle: "Sign in to see your prizes",
    prizesReason: "See what you've won, collect prizes and choose where they're sent.",
    signOut: "Sign out",
    socialLater: "Google and email sign-in are coming soon.",
  },
} as const;

/** The host's create-giveaway flow. Functions take the values they describe. */
export const create = {
  title: "New giveaway",
  step: (n: number, total: number) => `Step ${n} of ${total}`,
  audience: {
    heading: "Who's it for?",
    lead: "Pick one and we'll set everything up. You can change it on the next step.",
    community: {
      label: "My community",
      hint: "Meetups and groups · 10 winners · tonight",
    },
    followers: {
      label: "My followers",
      hint: "Social giveaway · 3 winners · starts in 15 min",
    },
    custom: { label: "Something else", hint: "Start small and set it up yourself" },
  },
  next: { prize: "Next", review: "Review" },
  prize: {
    heading: "The prize",
    name: "Giveaway name",
    amount: "Prize",
    token: "Paid in",
    runsOn: (chain: string) => `Runs on ${chain}. We pick the network from the token.`,
    winners: "Winners",
    fewer: "Fewer winners",
    more: "More winners",
  },
  reward: {
    heading: "How the prize is shared",
    balanced: { label: "Balanced", hint: "Every winner gets the same" },
    weighted: { label: "Weighted", hint: "Higher on the leaderboard, bigger prize" },
    random: { label: "Random", hint: "A surprise share for each place" },
    describeBalanced: (winners: number, each: string) =>
      `The top ${winners} players each get ${each}. Everyone who makes the cut is paid the same.`,
    describeWeighted: (winners: number, first: string, last: string) =>
      `The top ${winners} players win, and higher places win more: 1st gets ${first}, down to ${last} for ${ordinal(winners)}.`,
    describeRandom: (winners: number) =>
      `The top ${winners} players win, but each place gets a surprise share, so 1st isn't guaranteed the most. The shares are drawn when you publish and shown to everyone, so nobody can change them later.`,
    reshuffle: "Draw again",
    morePlaces: (n: number) => `+${n} more ${n === 1 ? "place" : "places"}`,
  },
  games: {
    heading: "The game",
    auto: { label: "Let FairDrops choose", hint: "A quick game that suits a big crowd" },
    pick: { label: "I'll choose", hint: "Pick a FairDrops game or one of your own" },
    builtIn: "FairDrops games",
    yours: "Your and partner games",
    noneYours: "Games you register under Developers show up here once approved.",
    mix: "Mix with FairDrops games",
    mixLater: "One game per giveaway for now. Mixing games is coming soon.",
    describeAuto:
      "We'll run Dice: each player rolls two dice three times within two minutes, and the highest total wins. It's fast, needs no knowledge, and works for any crowd.",
    describe: {
      dice: "Each player rolls two dice three times within two minutes. The highest total wins, and ties go to the best single roll.",
      quiz: "Timed multiple-choice questions. Most right answers wins; ties go to whoever answered fastest. Needs a question bank, set in Advanced settings.",
    } as Record<string, string>,
    describeExternal: (name: string) =>
      `Players play ${name} in its own app. Its server reports the scores, and they're checked like any other game.`,
  },
  start: { heading: "Starts", soon: "In 15 min", tonight: "Tonight 8:30", pick: "Pick a time" },
  startAt: "Start time",
  advanced: {
    toggle: "Advanced settings",
    lead: "Fine-tune the game. The defaults suit most giveaways.",
    rolls: "Rolls per player",
    window: "Play time (seconds)",
    bank: "Question bank id",
    bankHint: "The id of a question bank uploaded for quizzes.",
    questions: "Questions",
    secondsPerQuestion: "Seconds per question",
    minScore: "Minimum score to win",
    minScoreHint: "Players below this never win, even if there are spare places.",
  },
  review: {
    heading: "Review and lock",
    summary: (o: { winners: number; amount: string; game: string; when: string; share: string }) =>
      `Up to ${o.winners} players share ${o.amount}. They play ${o.game}, starting ${o.when}. ${o.share}`,
    shareBalanced: "Every winner gets the same.",
    shareWeighted: "Higher places get more.",
    shareRandom: "Each place gets the surprise share shown below.",
    rows: {
      prize: "Prize",
      network: "Network",
      winners: "Winners",
      game: "Game",
      starts: "Starts",
      leftovers: "Unclaimed prizes",
      leftoversValue: "Come back to you",
    },
    trust:
      "Your prize is locked in a public contract, so players can see it's real. Nobody, including us, can move it except to pay the winners or refund you. You can cancel for a full refund until it starts.",
    payHeading: "How you'll pay",
    wallet: { label: "Connect a wallet", hint: "Approve and lock from your browser wallet" },
    card: { label: "Card", hint: "Pay with a debit or credit card" },
    send: { label: "Send from any wallet", hint: "Get an address and send the prize to it" },
    lock: (amount: string) => `Lock ${amount}`,
    locking: "Locking",
    confirm: "Confirm in your wallet when asked.",
    cancelled: "You cancelled in your wallet. Nothing was locked.",
    needBank: "Quizzes need a question bank. Add its id in Advanced settings.",
  },
} as const;

function ordinal(n: number): string {
  const tens = n % 100;
  if (tens >= 11 && tens <= 13) return `${n}th`;
  return `${n}${["th", "st", "nd", "rd"][n % 10] ?? "th"}`;
}
