/**
 * Builds, tests and deploys the FairDrops subgraph. Each indexed chain gets its own Goldsky
 * deployment, rendered from subgraph.template.yaml with that chain's network name, contract
 * address and deployment block.
 *
 *   node scripts/subgraph.ts codegen
 *   node scripts/subgraph.ts build [chain-key...]
 *   node scripts/subgraph.ts test
 *   node scripts/subgraph.ts deploy <version> [chain-key...]
 *   node scripts/subgraph.ts promote <version> [chain-key...]
 *
 * With no chain keys, deploy and promote act on every indexed chain.
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { deployments } from "@fairdrops/contracts";
import { SUBGRAPH_TAG, chains, subgraphName, type Chain } from "@fairdrops/shared";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const template = join(packageRoot, "subgraph.template.yaml");

const HEADER = "# Generated by packages/subgraph/scripts/subgraph.ts. Do not edit.\n";

interface Target {
  chain: Chain & { subgraphNetwork: string };
  address: string;
  startBlock: number;
  manifest: string;
}

function main(): void {
  const [command, ...args] = process.argv.slice(2);
  switch (command) {
    case "codegen":
      codegen();
      break;
    case "build":
      build(select(args));
      break;
    case "test":
      codegen();
      run("graph", ["test"]);
      break;
    case "deploy": {
      const [version, ...keys] = args;
      deploy(requireVersion(version), select(keys));
      break;
    }
    case "promote": {
      const [version, ...keys] = args;
      promote(requireVersion(version), select(keys));
      break;
    }
    case undefined:
    default:
      fail(`Unknown command "${command ?? ""}". Expected codegen, build, test, deploy or promote.`);
  }
}

/**
 * Chains the subgraph runs on: deployed, not local, and supported by Goldsky. Local chains are
 * skipped because their deployments are not committed and change on every Anvil restart.
 */
function targets(): Target[] {
  const result: Target[] = [];
  for (const chain of chains) {
    if (chain.environment === "local" || chain.subgraphNetwork === null) continue;
    const deployment = deployments.find(
      (d) => d.chainId === chain.chainId && d.contract === "FairDrops",
    );
    if (!deployment) continue;
    result.push({
      chain: { ...chain, subgraphNetwork: chain.subgraphNetwork },
      address: deployment.address,
      startBlock: deployment.blockNumber,
      manifest: join(packageRoot, `subgraph.${chain.key}.yaml`),
    });
  }
  if (result.length === 0) fail("No FairDrops deployment is on a chain Goldsky can index.");
  return result;
}

function select(keys: string[]): Target[] {
  const all = targets();
  if (keys.length === 0) return all;
  return keys.map((key) => {
    const target = all.find((t) => t.chain.key === key);
    if (!target) {
      fail(`"${key}" is not an indexed chain. Indexed: ${all.map((t) => t.chain.key).join(", ")}`);
    }
    return target;
  });
}

function render(target: Target): string {
  const values: Record<string, string> = {
    chainName: target.chain.name,
    network: target.chain.subgraphNetwork,
    address: target.address,
    startBlock: String(target.startBlock),
  };
  const manifest = readFileSync(template, "utf8")
    .replace(/^#.*\n/gm, "")
    .replace(/\{\{(\w+)\}\}/g, (_match, key: string) => {
      const value = values[key];
      if (value === undefined) fail(`subgraph.template.yaml uses unknown value {{${key}}}`);
      return value;
    });
  return HEADER + manifest;
}

/**
 * Writes every chain's manifest, plus subgraph.yaml for the first chain so tools that expect the
 * default name (graph codegen, matchstick) work. Generated types do not depend on the chain.
 */
function writeManifests(): Target[] {
  const all = targets();
  for (const target of all) writeFileSync(target.manifest, render(target));
  writeFileSync(join(packageRoot, "subgraph.yaml"), render(all[0]!));
  return all;
}

function codegen(): void {
  writeManifests();
  run("graph", ["codegen", "subgraph.yaml", "--output-dir", "generated"]);
}

function build(selected: Target[]): void {
  codegen();
  for (const target of selected) {
    log(`Building ${target.chain.key} (${target.chain.subgraphNetwork})`);
    run("graph", [
      "build",
      target.manifest,
      "--output-dir",
      join("build", target.chain.key),
      "--skip-migrations",
    ]);
  }
}

function deploy(version: string, selected: Target[]): void {
  build(selected);
  for (const target of selected) {
    const name = `${subgraphName(target.chain)}/${version}`;
    log(`Deploying ${name}`);
    run("goldsky", ["subgraph", "deploy", name, "--path", join("build", target.chain.key)]);
  }
  log(
    `Deployed. Once each version has synced, point the worker at it with:\n` +
      `  pnpm --filter @fairdrops/subgraph subgraph:promote ${version} ${selected.map((t) => t.chain.key).join(" ")}`,
  );
}

/** Moves the tag the worker reads from to `version`. */
function promote(version: string, selected: Target[]): void {
  for (const target of selected) {
    const name = `${subgraphName(target.chain)}/${version}`;
    log(`Tagging ${name} as ${SUBGRAPH_TAG}`);
    run("goldsky", ["subgraph", "tag", "create", name, "--tag", SUBGRAPH_TAG]);
  }
}

function requireVersion(version: string | undefined): string {
  if (!version || !/^\d+\.\d+\.\d+$/.test(version)) {
    fail("Pass the subgraph version to deploy, e.g. 1.0.0");
  }
  return version;
}

function run(command: string, args: string[]): void {
  const result = spawnSync(command, args, { cwd: packageRoot, stdio: "inherit" });
  if (result.error) fail(`Could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) fail(`${command} ${args.join(" ")} exited with ${result.status}`);
}

function log(message: string): void {
  process.stdout.write(`${message}\n`);
}

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

main();
